package strmech

import (
	"fmt"
	ePref "github.com/MikeAustin71/errpref"
	"strings"
	"sync"
)

// textStrBuilderElectron - Provides helper methods for type
// TextStrBuilder.
//
type textStrBuilderElectron struct {
	lock *sync.Mutex
}

// lineBlank - Designed to produce one or more blank or empty lines
// of text. Each blank line will consist of a single new line
// character, '/n'.
//
// Consequently, the terms "blank lines" and "new lines" are
// synonymous as used here.
//
//
// ----------------------------------------------------------------
//
// Input Parameters
//
//  strBuilder                 *strings.Builder
//     - A pointer to an instance of strings.Builder. A formatted
//       string of text characters created by this method will be
//       written to this instance of strings.Builder.
//
//
//  numOfBlankLines            int
//     - The number of blank lines which will be generated by this
//       method.
//
//       If this value is less than one (+1), an error will be
//       returned. Likewise, if this value is greater than
//       one-million (1,000,000), an error will be returned.
//
//
//  errPrefDto                 *ePref.ErrPrefixDto
//     - This object encapsulates an error prefix string which is
//       included in all returned error messages. Usually, it
//       contains the name of the calling method or methods listed
//       as a function chain.
//
//       If no error prefix information is needed, set this
//       parameter to 'nil'.
//
//       Type ErrPrefixDto is included in the 'errpref' software
//       package, "github.com/MikeAustin71/errpref".
//
//
// ----------------------------------------------------------------
//
// Return Values
//
//  err                             error
//     - If this method completes successfully and no errors are
//       encountered, this return value is set to 'nil'. Otherwise,
//       if errors are encountered, this return value will contain
//       an appropriate error message.
//
//       If an error message is returned, the text value of input
//       parameter 'errorPrefix' will be inserted or prefixed at
//       the beginning of the error message.
//
func (txtBuilderElectron *textStrBuilderElectron) lineBlank(
	strBuilder *strings.Builder,
	numOfBlankLines int,
	errPrefDto *ePref.ErrPrefixDto) error {

	if txtBuilderElectron.lock == nil {
		txtBuilderElectron.lock = new(sync.Mutex)
	}

	txtBuilderElectron.lock.Lock()

	defer txtBuilderElectron.lock.Unlock()

	var ePrefix *ePref.ErrPrefixDto
	var err error

	ePrefix,
		err = ePref.ErrPrefixDto{}.NewFromErrPrefDto(
		errPrefDto,
		"textStrBuilderElectron."+
			"lineBlank()",
		"")

	if err != nil {
		return err
	}

	if strBuilder == nil {
		err = fmt.Errorf("%v\n"+
			"Error: Input parameter 'strBuilder' is invalid!\n"+
			"'strBuilder' has a 'nil' pointer.\n",
			ePrefix.String())

		return err
	}

	if numOfBlankLines < 1 {

		err = fmt.Errorf("%v\n"+
			"Error: Input parameter 'numOfBlankLines' is invalid!\n"+
			"'numOfBlankLines' has a value less than one (+1).\n"+
			"numOfBlankLines = '%v'\n",
			ePrefix.String(),
			numOfBlankLines)

		return err
	}

	if numOfBlankLines > 1000000 {

		err = fmt.Errorf("%v\n"+
			"Error: Input parameter 'numOfBlankLines' is invalid!\n"+
			"'numOfBlankLines' has a value greater than one-million (1,000,000).\n"+
			"numOfBlankLines = '%v'\n",
			ePrefix.String(),
			numOfBlankLines)

		return err
	}

	for i := 0; i < numOfBlankLines; i++ {

		strBuilder.WriteString("\n")

	}

	return err
}

// ptr - Returns a pointer to a new instance of
// textStrBuilderElectron.
//
func (txtBuilderElectron textStrBuilderElectron) ptr() *textStrBuilderElectron {

	if txtBuilderElectron.lock == nil {
		txtBuilderElectron.lock = new(sync.Mutex)
	}

	txtBuilderElectron.lock.Lock()

	defer txtBuilderElectron.lock.Unlock()

	return &textStrBuilderElectron{
		lock: new(sync.Mutex),
	}
}
